# Default values for nsm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: 4lie/nats-static-monitoring
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

endpoints:
  streaming:
    - /varz
    - /connz?subs=detail&auth=1&state=any
    - /routez?sub=detail
    - /gatewayz?accs=1
    - /leafz?subs=1
    - /streaming/serverz
    - /streaming/storez
    - /streaming/clientsz?subs=1
    - /streaming/channelsz?subs=1
  core:
    - /varz
    - /connz?subs=detail&auth=1&state=any
    - /routez?sub=detail
    - /gatewayz?accs=1
    - /leafz?subs=1
    - /subsz?subs=1

config:
  nats:
    - server: http://nats-01.4lie.ir:8222
      type: nats-core
      alias: nats-01.4lie.ir
      connect-timeout: 1s
    - server: http://nats-streaming-01.4lie.ir:8222
      type: nats-streaming
      alias: nats-streaming-01.4lie.ir
      connect-timeout: 1s
  elasticsearch:
    servers:
      - http://elasticsearch-01.4lie.ir:9200
