---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nsm.fullname" . }}
  labels:
    {{- include "nsm.labels" . | nindent 4 }}
data:
  config.yaml: {{ tpl (.Files.Get "conf/app.yaml") . | quote }}
