---
logger:
  level: debug

monitor-servers:
  {{- range .Values.config.nats -}}
  - server: {{ .server }}
    type: {{ .type }}
    alias: {{ .alias }}
    connect-timeout: {{ .connect-timeout }}
    {{- if eq .type "nats-streaming" -}}
    endpoints: .Values.endpoints.streaming
    {{- end -}}
    {{- if eq .type "nats-core" -}}
    endpoints: .Values.endpoints.core
    {{- end -}}
  {{- end -}}

elasticsearch:
    {{- toYaml .Values.elastics.servers | nindent 1 }}

scheduler:
  cron-pattern: "0/10 * * * * *"
